// SPDX-License-Identifier: GPL-2.0-only
/*
 * Copyright (c) 2020, The Linux Foundation. All rights reserved.
 */

#include <linux/regmap.h>
#include <linux/device.h>
#include "besbev-registers.h"

extern const u8 besbev_reg_access_analog[
			BESBEV_REG(BESBEV_ANALOG_REGISTERS_MAX_SIZE)];
extern const u8 besbev_reg_access_digital[
			BESBEV_REG(BESBEV_DIGITAL_REGISTERS_MAX_SIZE)];

static const struct reg_default besbev_defaults[] = {
	{ BESBEV_ANA_MICBIAS_MICB_1_2_EN,        0x01 },
	{ BESBEV_ANA_MICBIAS_MICB_3_EN,          0x00 },
	{ BESBEV_ANA_MICBIAS_LDO_1_SETTING,      0x21 },
	{ BESBEV_ANA_MICBIAS_LDO_1_CTRL,         0x01 },
	{ BESBEV_ANA_TX_AMIC1,                   0x00 },
	{ BESBEV_ANA_TX_AMIC2,                   0x00 },
	{ BESBEV_ANA_NCP_EN,                     0x00 },
	{ BESBEV_ANA_NCP_VCTRL,                  0xA7 },
	{ BESBEV_ANA_HPHPA_CNP_CTL_1,            0x54 },
	{ BESBEV_ANA_HPHPA_CNP_CTL_2,            0x2B },
	{ BESBEV_ANA_HPHPA_PA_STATUS,            0x00 },
	{ BESBEV_ANA_HPHPA_FSM_CLK,              0x12 },
	{ BESBEV_ANA_HPHPA_L_GAIN,               0x00 },
	{ BESBEV_ANA_HPHPA_R_GAIN,               0x00 },
	{ BESBEV_SWR_HPHPA_HD2,                  0x1B },
	{ BESBEV_ANA_HPHPA_SPARE_CTL,            0x02 },
	{ BESBEV_ANA_SURGE_EN,                   0x38 },
	{ BESBEV_ANA_COMBOPA_CTL,                0x35 },
	{ BESBEV_ANA_COMBOPA_CTL_4,              0x84 },
	{ BESBEV_ANA_COMBOPA_CTL_5,              0x05 },
	{ BESBEV_ANA_RXLDO_CTL,                  0x86 },
	{ BESBEV_ANA_MBIAS_EN,                   0x00 },
	{ BESBEV_DIG_SWR_CHIP_ID0,               0x00 },
	{ BESBEV_DIG_SWR_CHIP_ID1,               0x00 },
	{ BESBEV_DIG_SWR_CHIP_ID2,               0x0C },
	{ BESBEV_DIG_SWR_CHIP_ID3,               0x01 },
	{ BESBEV_DIG_SWR_SWR_TX_CLK_RATE,        0x00 },
	{ BESBEV_DIG_SWR_CDC_RST_CTL,            0x03 },
	{ BESBEV_DIG_SWR_TOP_CLK_CFG,            0x00 },
	{ BESBEV_DIG_SWR_CDC_RX_CLK_CTL,         0x00 },
	{ BESBEV_DIG_SWR_CDC_TX_CLK_CTL,         0x33 },
	{ BESBEV_DIG_SWR_SWR_RST_EN,             0x00 },
	{ BESBEV_DIG_SWR_CDC_RX_RST,             0x00 },
	{ BESBEV_DIG_SWR_CDC_RX0_CTL,            0xFC },
	{ BESBEV_DIG_SWR_CDC_RX1_CTL,            0xFC },
	{ BESBEV_DIG_SWR_CDC_TX_ANA_MODE_0_1,    0x00 },
	{ BESBEV_DIG_SWR_CDC_COMP_CTL_0,         0x00 },
	{ BESBEV_DIG_SWR_CDC_RX_DELAY_CTL,       0x66 },
	{ BESBEV_DIG_SWR_CDC_RX_GAIN_0,          0x55 },
	{ BESBEV_DIG_SWR_CDC_RX_GAIN_1,          0xA9 },
	{ BESBEV_DIG_SWR_CDC_RX_GAIN_CTL,        0x00 },
	{ BESBEV_DIG_SWR_CDC_TX0_CTL,            0x68 },
	{ BESBEV_DIG_SWR_CDC_TX1_CTL,            0x68 },
	{ BESBEV_DIG_SWR_CDC_TX_RST,             0x00 },
	{ BESBEV_DIG_SWR_CDC_REQ0_CTL,           0x01 },
	{ BESBEV_DIG_SWR_CDC_REQ1_CTL,           0x01 },
	{ BESBEV_DIG_SWR_CDC_RST,                0x00 },
	{ BESBEV_DIG_SWR_CDC_AMIC_CTL,           0x02 },
	{ BESBEV_DIG_SWR_CDC_DMIC_CTL,           0x00 },
	{ BESBEV_DIG_SWR_CDC_DMIC1_CTL,          0x00 },
	{ BESBEV_DIG_SWR_CDC_DMIC1_RATE,         0x01 },
	{ BESBEV_DIG_SWR_PDM_WD_CTL0,            0x00 },
	{ BESBEV_DIG_SWR_PDM_WD_CTL1,            0x00 },
	{ BESBEV_DIG_SWR_INTR_MODE,              0x00 },
	{ BESBEV_DIG_SWR_INTR_MASK_0,            0xFF },
	{ BESBEV_DIG_SWR_INTR_MASK_1,            0x7F },
	{ BESBEV_DIG_SWR_INTR_MASK_2,            0x0C },
	{ BESBEV_DIG_SWR_INTR_STATUS_0,          0x00 },
	{ BESBEV_DIG_SWR_INTR_STATUS_1,          0x00 },
	{ BESBEV_DIG_SWR_INTR_STATUS_2,          0x00 },
	{ BESBEV_DIG_SWR_INTR_CLEAR_0,           0x00 },
	{ BESBEV_DIG_SWR_INTR_CLEAR_1,           0x00 },
	{ BESBEV_DIG_SWR_INTR_CLEAR_2,           0x00 },
	{ BESBEV_DIG_SWR_INTR_LEVEL_0,           0x00 },
	{ BESBEV_DIG_SWR_INTR_LEVEL_1,           0x2A },
	{ BESBEV_DIG_SWR_INTR_LEVEL_2,           0x00 },
	{ BESBEV_DIG_SWR_CDC_CONN_RX0_CTL,       0x00 },
	{ BESBEV_DIG_SWR_CDC_CONN_RX1_CTL,       0x00 },
	{ BESBEV_DIG_SWR_LOOP_BACK_MODE,         0x00 },
	{ BESBEV_DIG_SWR_DRIVE_STRENGTH_0,       0x00 },
	{ BESBEV_DIG_SWR_DIG_DEBUG_CTL,          0x00 },
	{ BESBEV_DIG_SWR_DIG_DEBUG_EN,           0x00 },
	{ BESBEV_DIG_SWR_DEM_BYPASS_DATA0,       0x55 },
	{ BESBEV_DIG_SWR_DEM_BYPASS_DATA1,       0x55 },
	{ BESBEV_DIG_SWR_DEM_BYPASS_DATA2,       0x55 },
	{ BESBEV_DIG_SWR_DEM_BYPASS_DATA3,       0x01 },
	{BESBEV_REF_CTRL,                   0xD5},
	{BESBEV_TEST_CTL_0,                 0x06},
	{BESBEV_BIAS_0,                     0xD2},
	{BESBEV_OP_CTL,                     0xE0},
	{BESBEV_IREF_CTL,                   0x57},
	{BESBEV_ISENS_CTL,                  0x47},
	{BESBEV_CLK_CTL,                    0x87},
	{BESBEV_TEST_CTL_1,                 0x00},
	{BESBEV_BIAS_1,                     0x51},
	{BESBEV_ADC_CTL,                    0x01},
	{BESBEV_DOUT_MSB,                   0x00},
	{BESBEV_DOUT_LSB,                   0x00},
	{BESBEV_VBAT_SNS,                   0x40},
	{BESBEV_ITRIM_CODE,                 0x9F},
	{BESBEV_EN,                         0x20},
	{BESBEV_OVERRIDE1,                  0x00},
	{BESBEV_OVERRIDE2,                  0x08},
	{BESBEV_VSENSE1,                    0xD3},
	{BESBEV_ISENSE1,                    0xD4},
	{BESBEV_ISENSE2,                    0x20},
	{BESBEV_ISENSE_CAL,                 0x00},
	{BESBEV_MISC,                       0x08},
	{BESBEV_ADC_0,                      0x00},
	{BESBEV_ADC_1,                      0x00},
	{BESBEV_ADC_2,                      0x40},
	{BESBEV_ADC_3,                      0x80},
	{BESBEV_ADC_4,                      0x25},
	{BESBEV_ADC_5,                      0x25},
	{BESBEV_ADC_6,                      0x08},
	{BESBEV_ADC_7,                      0x81},
	{BESBEV_STATUS,                     0x00},
	{BESBEV_DAC_CTRL_REG,               0x53},
	{BESBEV_DAC_EN_DEBUG_REG,           0x00},
	{BESBEV_DAC_OPAMP_BIAS1_REG,        0x48},
	{BESBEV_DAC_OPAMP_BIAS2_REG,        0x48},
	{BESBEV_DAC_VCM_CTRL_REG,           0x88},
	{BESBEV_DAC_VOLTAGE_CTRL_REG,       0xA5},
	{BESBEV_ATEST1_REG,                 0x00},
	{BESBEV_ATEST2_REG,                 0x00},
	{BESBEV_SPKR_TOP_BIAS_REG1,         0x6A},
	{BESBEV_SPKR_TOP_BIAS_REG2,         0x65},
	{BESBEV_SPKR_TOP_BIAS_REG3,         0x55},
	{BESBEV_SPKR_TOP_BIAS_REG4,         0xA9},
	{BESBEV_SPKR_CLIP_DET_REG,          0x9C},
	{BESBEV_SPKR_DRV_LF_BLK_EN,         0x0F},
	{BESBEV_SPKR_DRV_LF_EN,             0x0A},
	{BESBEV_SPKR_DRV_LF_MASK_DCC_CTL,   0x00},
	{BESBEV_SPKR_DRV_LF_MISC_CTL,       0x3A},
	{BESBEV_SPKR_DRV_LF_REG_GAIN,       0x00},
	{BESBEV_SPKR_DRV_OS_CAL_CTL,        0x00},
	{BESBEV_SPKR_DRV_OS_CAL_CTL1,       0x90},
	{BESBEV_SPKR_PWM_CLK_CTL,           0x00},
	{BESBEV_SPKR_PDRV_HS_CTL,           0x52},
	{BESBEV_SPKR_PDRV_LS_CTL,           0x48},
	{BESBEV_SPKR_PWRSTG_DBG,            0x08},
	{BESBEV_SPKR_OCP_CTL,               0xE2},
	{BESBEV_SPKR_BBM_CTL,               0x92},
	{BESBEV_PA_STATUS0,                 0x00},
	{BESBEV_PA_STATUS1,                 0x00},
	{BESBEV_PA_STATUS2,                 0x80},
	{BESBEV_EN_CTRL,                    0x44},
	{BESBEV_CURRENT_LIMIT,              0xCC},
	{BESBEV_IBIAS1,                     0x00},
	{BESBEV_IBIAS2,                     0x00},
	{BESBEV_IBIAS3,                     0x00},
	{BESBEV_LDO_PROG,                   0x02},
	{BESBEV_STABILITY_CTRL1,            0x8E},
	{BESBEV_STABILITY_CTRL2,            0x10},
	{BESBEV_PWRSTAGE_CTRL1,             0x06},
	{BESBEV_PWRSTAGE_CTRL2,             0x00},
	{BESBEV_BYPASS_1,                   0x19},
	{BESBEV_BYPASS_2,                   0x13},
	{BESBEV_ZX_CTRL_1,                  0xF0},
	{BESBEV_ZX_CTRL_2,                  0x04},
	{BESBEV_MISC1,                      0x06},
	{BESBEV_MISC2,                      0xA0},
	{BESBEV_GMAMP_SUP1,                 0x82},
	{BESBEV_PWRSTAGE_CTRL3,             0x39},
	{BESBEV_PWRSTAGE_CTRL4,             0x5F},
	{BESBEV_TEST1,                      0x00},
	{BESBEV_SPARE1,                     0x00},
	{BESBEV_SPARE2,                     0x00},
	{BESBEV_PON_CTL_0,                  0x10},
	{BESBEV_PON_CLT_1,                  0xE0},
	{BESBEV_PON_CTL_2,                  0x90},
	{BESBEV_PON_CTL_3,                  0x70},
	{BESBEV_CKWD_CTL_0,                 0x34},
	{BESBEV_CKWD_CTL_1,                 0x0F},
	{BESBEV_CKWD_CTL_2,                 0x00},
	{BESBEV_CKSK_CTL_0,                 0x00},
	{BESBEV_PADSW_CTL_0,                0x00},
	{BESBEV_TEST_0,                     0x00},
	{BESBEV_TEST_1,                     0x00},
	{BESBEV_STATUS_0,                   0x00},
	{BESBEV_STATUS_1,                   0x00},
	{BESBEV_CHIP_ID0,                   0x00},
	{BESBEV_CHIP_ID1,                   0x00},
	{BESBEV_CHIP_ID2,                   0x02},
	{BESBEV_CHIP_ID3,                   0x02},
	{BESBEV_BUS_ID,                     0x00},
	{BESBEV_CDC_RST_CTL,                0x01},
	{BESBEV_TOP_CLK_CFG,                0x00},
	{BESBEV_CDC_PATH_MODE,              0x00},
	{BESBEV_CDC_CLK_CTL,                0xFF},
	{BESBEV_SWR_RESET_EN,               0x00},
	{BESBEV_RESET_CTL,                  0x00},
	{BESBEV_PA_FSM_CTL,                 0x00},
	{BESBEV_PA_FSM_TIMER0,              0x80},
	{BESBEV_PA_FSM_TIMER1,              0x80},
	{BESBEV_PA_FSM_STA,                 0x00},
	{BESBEV_PA_FSM_ERR_COND,            0x00},
	{BESBEV_PA_FSM_MSK,                 0x00},
	{BESBEV_PA_FSM_BYP,                 0x01},
	{BESBEV_PA_FSM_DBG,                 0x00},
	{BESBEV_TADC_VALUE_CTL,             0x03},
	{BESBEV_TEMP_DETECT_CTL,            0x01},
	{BESBEV_TEMP_MSB,                   0x00},
	{BESBEV_TEMP_LSB,                   0x00},
	{BESBEV_TEMP_CONFIG0,               0x00},
	{BESBEV_TEMP_CONFIG1,               0x00},
	{BESBEV_VBAT_ADC_FLT_CTL,           0x00},
	{BESBEV_VBAT_DIN_MSB,               0x00},
	{BESBEV_VBAT_DIN_LSB,               0x00},
	{BESBEV_VBAT_DOUT,                  0x00},
	{BESBEV_SDM_PDM9_LSB,               0x00},
	{BESBEV_SDM_PDM9_MSB,               0x00},
	{BESBEV_CDC_RX_CTL,                 0xFE},
	{BESBEV_CDC_SPK_DSM_A1_0,           0x00},
	{BESBEV_CDC_SPK_DSM_A1_1,           0x01},
	{BESBEV_CDC_SPK_DSM_A2_0,           0x96},
	{BESBEV_CDC_SPK_DSM_A2_1,           0x09},
	{BESBEV_CDC_SPK_DSM_A3_0,           0xAB},
	{BESBEV_CDC_SPK_DSM_A3_1,           0x05},
	{BESBEV_CDC_SPK_DSM_A4_0,           0x1C},
	{BESBEV_CDC_SPK_DSM_A4_1,           0x02},
	{BESBEV_CDC_SPK_DSM_A5_0,           0x17},
	{BESBEV_CDC_SPK_DSM_A5_1,           0x02},
	{BESBEV_CDC_SPK_DSM_A6_0,           0xAA},
	{BESBEV_CDC_SPK_DSM_A7_0,           0xE3},
	{BESBEV_CDC_SPK_DSM_C_0,            0x69},
	{BESBEV_CDC_SPK_DSM_C_1,            0x54},
	{BESBEV_CDC_SPK_DSM_C_2,            0x02},
	{BESBEV_CDC_SPK_DSM_C_3,            0x15},
	{BESBEV_CDC_SPK_DSM_R1,             0xA4},
	{BESBEV_CDC_SPK_DSM_R2,             0xB5},
	{BESBEV_CDC_SPK_DSM_R3,             0x86},
	{BESBEV_CDC_SPK_DSM_R4,             0x85},
	{BESBEV_CDC_SPK_DSM_R5,             0xAA},
	{BESBEV_CDC_SPK_DSM_R6,             0xE2},
	{BESBEV_CDC_SPK_DSM_R7,             0x62},
	{BESBEV_CDC_SPK_GAIN_PDM_0,         0x00},
	{BESBEV_CDC_SPK_GAIN_PDM_1,         0xFC},
	{BESBEV_CDC_SPK_GAIN_PDM_2,         0x05},
	{BESBEV_PDM_WD_CTL,                 0x00},
	{BESBEV_DEM_BYPASS_DATA0,           0x00},
	{BESBEV_DEM_BYPASS_DATA1,           0x00},
	{BESBEV_DEM_BYPASS_DATA2,           0x00},
	{BESBEV_DEM_BYPASS_DATA3,           0x00},
	{BESBEV_WAVG_CTL,                   0x06},
	{BESBEV_WAVG_LRA_PER_0,             0xD1},
	{BESBEV_WAVG_LRA_PER_1,             0x00},
	{BESBEV_WAVG_DELTA_THETA_0,         0xE6},
	{BESBEV_WAVG_DELTA_THETA_1,         0x04},
	{BESBEV_WAVG_DIRECT_AMP_0,          0x50},
	{BESBEV_WAVG_DIRECT_AMP_1,          0x00},
	{BESBEV_WAVG_PTRN_AMP0_0,           0x50},
	{BESBEV_WAVG_PTRN_AMP0_1,           0x00},
	{BESBEV_WAVG_PTRN_AMP1_0,           0x50},
	{BESBEV_WAVG_PTRN_AMP1_1,           0x00},
	{BESBEV_WAVG_PTRN_AMP2_0,           0x50},
	{BESBEV_WAVG_PTRN_AMP2_1,           0x00},
	{BESBEV_WAVG_PTRN_AMP3_0,           0x50},
	{BESBEV_WAVG_PTRN_AMP3_1,           0x00},
	{BESBEV_WAVG_PTRN_AMP4_0,           0x50},
	{BESBEV_WAVG_PTRN_AMP4_1,           0x00},
	{BESBEV_WAVG_PTRN_AMP5_0,           0x50},
	{BESBEV_WAVG_PTRN_AMP5_1,           0x00},
	{BESBEV_WAVG_PTRN_AMP6_0,           0x50},
	{BESBEV_WAVG_PTRN_AMP6_1,           0x00},
	{BESBEV_WAVG_PTRN_AMP7_0,           0x50},
	{BESBEV_WAVG_PTRN_AMP7_1,           0x00},
	{BESBEV_WAVG_PER_0_1,               0x88},
	{BESBEV_WAVG_PER_2_3,               0x88},
	{BESBEV_WAVG_PER_4_5,               0x88},
	{BESBEV_WAVG_PER_6_7,               0x88},
	{BESBEV_WAVG_STA,                   0x00},
	{BESBEV_DRE_CTL_0,                  0x70},
	{BESBEV_DRE_CTL_1,                  0x08},
	{BESBEV_DRE_IDLE_DET_CTL,           0x1F},
	{BESBEV_CLSH_CTL_0,                 0x37},
	{BESBEV_CLSH_CTL_1,                 0x81},
	{BESBEV_CLSH_V_HD_PA,               0x0F},
	{BESBEV_CLSH_V_PA_MIN,              0x00},
	{BESBEV_CLSH_OVRD_VAL,              0x00},
	{BESBEV_CLSH_HARD_MAX,              0xFF},
	{BESBEV_CLSH_SOFT_MAX,              0xF5},
	{BESBEV_CLSH_SIG_DP,                0x00},
	{BESBEV_TAGC_CTL,                   0x10},
	{BESBEV_TAGC_TIME,                  0x20},
	{BESBEV_TAGC_E2E_GAIN,              0x02},
	{BESBEV_TAGC_FORCE_VAL,             0x00},
	{BESBEV_VAGC_CTL,                   0x00},
	{BESBEV_VAGC_TIME,                  0x08},
	{BESBEV_VAGC_ATTN_LVL_1_2,          0x21},
	{BESBEV_VAGC_ATTN_LVL_3,            0x03},
	{BESBEV_INTR_MODE,                  0x00},
	{BESBEV_INTR_MASK0,                 0x90},
	{BESBEV_INTR_MASK1,                 0x00},
	{BESBEV_INTR_STATUS0,               0x00},
	{BESBEV_INTR_STATUS1,               0x00},
	{BESBEV_INTR_CLEAR0,                0x00},
	{BESBEV_INTR_CLEAR1,                0x00},
	{BESBEV_INTR_LEVEL0,                0x00},
	{BESBEV_INTR_LEVEL1,                0x00},
	{BESBEV_INTR_SET0,                  0x00},
	{BESBEV_INTR_SET1,                  0x00},
	{BESBEV_INTR_TEST0,                 0x00},
	{BESBEV_INTR_TEST1,                 0x00},
	{BESBEV_OTP_CTRL0,                  0x00},
	{BESBEV_OTP_CTRL1,                  0x00},
	{BESBEV_HDRIVE_CTL_GROUP1,          0x00},
	{BESBEV_PIN_CTL,                    0x04},
	{BESBEV_PIN_CTL_OE,                 0x00},
	{BESBEV_PIN_WDATA_IOPAD,            0x00},
	{BESBEV_PIN_STATUS,                 0x00},
	{BESBEV_I2C_SLAVE_CTL,              0x00},
	{BESBEV_PDM_TEST_MODE,              0x00},
	{BESBEV_ATE_TEST_MODE,              0x00},
	{BESBEV_DIG_DEBUG_MODE,             0x00},
	{BESBEV_DIG_DEBUG_SEL,              0x00},
	{BESBEV_DIG_DEBUG_EN,               0x00},
	{BESBEV_SWR_HM_TEST0,               0x08},
	{BESBEV_SWR_HM_TEST1,               0x00},
	{BESBEV_SWR_PAD_CTL,                0x37},
	{BESBEV_TADC_DETECT_DBG_CTL,        0x00},
	{BESBEV_TADC_DEBUG_MSB,             0x00},
	{BESBEV_TADC_DEBUG_LSB,             0x00},
	{BESBEV_SAMPLE_EDGE_SEL,            0x7F},
	{BESBEV_SWR_EDGE_SEL,               0x00},
	{BESBEV_TEST_MODE_CTL,              0x04},
	{BESBEV_IOPAD_CTL,                  0x00},
	{BESBEV_ANA_CSR_DBG_ADD,            0x00},
	{BESBEV_ANA_CSR_DBG_CTL,            0x12},
	{BESBEV_SPARE_R,                    0x00},
	{BESBEV_SPARE_0,                    0x00},
	{BESBEV_SPARE_1,                    0x00},
	{BESBEV_SPARE_2,                    0x00},
	{BESBEV_SCODE,                      0x00},
	{BESBEV_OTP_REG_0,                  0x05},
	{BESBEV_OTP_REG_1,                  0xFF},
	{BESBEV_OTP_REG_2,                  0xC0},
	{BESBEV_OTP_REG_3,                  0xFF},
	{BESBEV_OTP_REG_4,                  0xC0},
	{BESBEV_OTP_REG_5,                  0xFF},
	{BESBEV_OTP_REG_6,                  0xFF},
	{BESBEV_OTP_REG_7,                  0xFF},
	{BESBEV_OTP_REG_8,                  0xFF},
	{BESBEV_OTP_REG_9,                  0xFF},
	{BESBEV_OTP_REG_10,                 0xFF},
	{BESBEV_OTP_REG_11,                 0xFF},
	{BESBEV_OTP_REG_12,                 0xFF},
	{BESBEV_OTP_REG_13,                 0xFF},
	{BESBEV_OTP_REG_14,                 0xFF},
	{BESBEV_OTP_REG_15,                 0xFF},
	{BESBEV_OTP_REG_16,                 0xFF},
	{BESBEV_OTP_REG_17,                 0xFF},
	{BESBEV_OTP_REG_18,                 0xFF},
	{BESBEV_OTP_REG_19,                 0xFF},
	{BESBEV_OTP_REG_20,                 0xFF},
	{BESBEV_OTP_REG_21,                 0xFF},
	{BESBEV_OTP_REG_22,                 0xFF},
	{BESBEV_OTP_REG_23,                 0xFF},
	{BESBEV_OTP_REG_24,                 0x37},
	{BESBEV_OTP_REG_25,                 0x3F},
	{BESBEV_OTP_REG_26,                 0x03},
	{BESBEV_OTP_REG_27,                 0x00},
	{BESBEV_OTP_REG_28,                 0x00},
	{BESBEV_OTP_REG_29,                 0x00},
	{BESBEV_OTP_REG_30,                 0x00},
	{BESBEV_OTP_REG_31,                 0x03},
	{BESBEV_OTP_REG_32,                 0x00},
	{BESBEV_OTP_REG_33,                 0xFF},
	{BESBEV_OTP_REG_34,                 0x00},
	{BESBEV_OTP_REG_35,                 0x00},
	{BESBEV_OTP_REG_63,                 0x40},
	{BESBEV_EMEM_0,                     0x00},
	{BESBEV_EMEM_1,                     0x00},
	{BESBEV_EMEM_2,                     0x00},
	{BESBEV_EMEM_3,                     0x00},
	{BESBEV_EMEM_4,                     0x00},
	{BESBEV_EMEM_5,                     0x00},
	{BESBEV_EMEM_6,                     0x00},
	{BESBEV_EMEM_7,                     0x00},
	{BESBEV_EMEM_8,                     0x00},
	{BESBEV_EMEM_9,                     0x00},
	{BESBEV_EMEM_10,                    0x00},
	{BESBEV_EMEM_11,                    0x00},
	{BESBEV_EMEM_12,                    0x00},
	{BESBEV_EMEM_13,                    0x00},
	{BESBEV_EMEM_14,                    0x00},
	{BESBEV_EMEM_15,                    0x00},
	{BESBEV_EMEM_16,                    0x00},
	{BESBEV_EMEM_17,                    0x00},
	{BESBEV_EMEM_18,                    0x00},
	{BESBEV_EMEM_19,                    0x00},
	{BESBEV_EMEM_20,                    0x00},
	{BESBEV_EMEM_21,                    0x00},
	{BESBEV_EMEM_22,                    0x00},
	{BESBEV_EMEM_23,                    0x00},
	{BESBEV_EMEM_24,                    0x00},
	{BESBEV_EMEM_25,                    0x00},
	{BESBEV_EMEM_26,                    0x00},
	{BESBEV_EMEM_27,                    0x00},
	{BESBEV_EMEM_28,                    0x00},
	{BESBEV_EMEM_29,                    0x00},
	{BESBEV_EMEM_30,                    0x00},
	{BESBEV_EMEM_31,                    0x00},
	{BESBEV_EMEM_32,                    0x00},
	{BESBEV_EMEM_33,                    0x00},
	{BESBEV_EMEM_34,                    0x00},
	{BESBEV_EMEM_35,                    0x00},
	{BESBEV_EMEM_36,                    0x00},
	{BESBEV_EMEM_37,                    0x00},
	{BESBEV_EMEM_38,                    0x00},
	{BESBEV_EMEM_39,                    0x00},
	{BESBEV_EMEM_40,                    0x00},
	{BESBEV_EMEM_41,                    0x00},
	{BESBEV_EMEM_42,                    0x00},
	{BESBEV_EMEM_43,                    0x00},
	{BESBEV_EMEM_44,                    0x00},
	{BESBEV_EMEM_45,                    0x00},
	{BESBEV_EMEM_46,                    0x00},
	{BESBEV_EMEM_47,                    0x00},
	{BESBEV_EMEM_48,                    0x00},
	{BESBEV_EMEM_49,                    0x00},
	{BESBEV_EMEM_50,                    0x00},
	{BESBEV_EMEM_51,                    0x00},
	{BESBEV_EMEM_52,                    0x00},
	{BESBEV_EMEM_53,                    0x00},
	{BESBEV_EMEM_54,                    0x00},
	{BESBEV_EMEM_55,                    0x00},
	{BESBEV_EMEM_56,                    0x00},
	{BESBEV_EMEM_57,                    0x00},
	{BESBEV_EMEM_58,                    0x00},
	{BESBEV_EMEM_59,                    0x00},
	{BESBEV_EMEM_60,                    0x00},
	{BESBEV_EMEM_61,                    0x00},
	{BESBEV_EMEM_62,                    0x00},
	{BESBEV_EMEM_63,                    0x00},
};

static bool besbev_readable_register(struct device *dev, unsigned int reg)
{
	if (reg > BESBEV_ANA_BASE_ADDR && reg <
				BESBEV_ANALOG_REGISTERS_MAX_SIZE)
		return besbev_reg_access_analog[BESBEV_REG(reg)] & RD_REG;
	if (reg > BESBEV_DIG_BASE_ADDR && reg <
				BESBEV_DIGITAL_REGISTERS_MAX_SIZE)
		return besbev_reg_access_digital[BESBEV_REG(reg)] & RD_REG;
	return 0;
}

static bool besbev_writeable_register(struct device *dev, unsigned int reg)
{
	if (reg > BESBEV_ANA_BASE_ADDR && reg <
					BESBEV_ANALOG_REGISTERS_MAX_SIZE)
		return besbev_reg_access_analog[BESBEV_REG(reg)] & WR_REG;
	if (reg > BESBEV_DIG_BASE_ADDR && reg <
					BESBEV_DIGITAL_REGISTERS_MAX_SIZE)
		return besbev_reg_access_digital[BESBEV_REG(reg)] & WR_REG;
	return 0;
}

static bool besbev_volatile_register(struct device *dev, unsigned int reg)
{
	if (reg > BESBEV_ANA_BASE_ADDR && reg <
					BESBEV_ANALOG_REGISTERS_MAX_SIZE)
		if ((besbev_reg_access_analog[BESBEV_REG(reg)] & RD_REG)
		    && !(besbev_reg_access_analog[BESBEV_REG(reg)] & WR_REG))
			return true;
	if (reg > BESBEV_DIG_BASE_ADDR && reg <
					BESBEV_DIGITAL_REGISTERS_MAX_SIZE)
		if ((besbev_reg_access_digital[BESBEV_REG(reg)] & RD_REG)
		    && !(besbev_reg_access_digital[BESBEV_REG(reg)] & WR_REG))
			return true;
	return 0;
}

struct regmap_config besbev_regmap_config = {
	.name = "besbev_csr",
	.reg_bits = 16,
	.val_bits = 8,
	.cache_type = REGCACHE_RBTREE,
	.reg_defaults = besbev_defaults,
	.num_reg_defaults = ARRAY_SIZE(besbev_defaults),
	.max_register = BESBEV_ANALOG_MAX_REGISTER +
				BESBEV_DIGITAL_MAX_REGISTER,
	.readable_reg = besbev_readable_register,
	.writeable_reg = besbev_writeable_register,
	.volatile_reg = besbev_volatile_register,
	.can_multi_write = true,
};
