/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2017-2018, The Linux Foundation. All rights reserved.
 *
 * Copyright (c) 2022 Qualcomm Innovation Center, Inc. All rights reserved.
 */

#define CONFIG_PINCTRL_WCD 1
#define CONFIG_SND_SOC_WCD934X 1
#define CONFIG_SND_SOC_MSM_SDW 1
#define CONFIG_SND_SOC_WCD9XXX_V2 1
#define CONFIG_SND_SOC_WCD_MBHC 1
#define CONFIG_SND_SOC_WSA881X 1
#define CONFIG_SND_SOC_WCD_DSP_MGR 1
#define CONFIG_SND_SOC_WCD934X_MBHC 1
#define CONFIG_SND_SOC_WCD934X_DSD 1
#define CONFIG_MSM_QDSP6V2_CODECS 1
#define CONFIG_MSM_QDSP6_APRV3_RPMSG 1
#define CONFIG_SND_SOC_MSM_QDSP6V2_INTF 1
#define CONFIG_MSM_ADSP_LOADER 1
#define CONFIG_REGMAP_SWR 1
#define CONFIG_SND_SOC_MSM_HOSTLESS_PCM 1
#define CONFIG_SND_SOC_POORWILLS 1
#define CONFIG_SOUNDWIRE 1
#define CONFIG_SOUNDWIRE_WCD_CTRL 1
#define CONFIG_SND_SOC_QDSP6V2 1
#define CONFIG_MSM_CDC_PINCTRL 1
#define CONFIG_WCD9XXX_CODEC_CORE 1
#define CONFIG_SND_SOC_WCD_MBHC_ADC 1
#define CONFIG_QTI_PP 1
#define CONFIG_SND_HWDEP_ROUTING 1
#define CONFIG_SND_SOC_MACHINE_SDXPOORWILLS 1
#define CONFIG_SND_SOC_MSM_STUB 1
#define CONFIG_SLIM_DISABLED 1
#define CONFIG_LSM_DISABLED 1
#define CONFIG_APTX_DEC_DISABLED 1
#define CONFIG_DOLBY_DS2_DISABLED 1
#define CONFIG_DTS_SRS_TM_DISABLED 1
#define CONFIG_SOURCE_TRACKING_DISABLED 1
#define CONFIG_DOLBY_DAP_DISABLED 1
#define CONFIG_MSM_QDSP6_NOTIFIER 1
#define CONFIG_SND_EVENT 1
#define CONFIG_MSM_QDSP6_SSR 1
